#pragma once

#include "core_pins.h"
void logg(uint8_t c);
void log_write(char *txt, uint32_t val);

//#define USB2_SERIAL
//#define USB2_SEREMU
//#define USB2_MTPDISK


#if defined(__MK66FX1M0__)
	#define USB2_DEVICEADDR USBHS_DEVICEADDR
	#define USB2_USBCMD USBHS_USBCMD
	#define USB2_USBSTS USBHS_USBSTS
	#define USB2_ENDPTSETUPSTAT USBHS_EPSETUPSR
	#define USB2_ENDPTPRIME  USBHS_EPPRIME
	#define USB2_ENDPTSTATUS USBHS_EPSR
	#define USB2_ENDPTCTRL0 USBHS_EPCR0
	#define USB2_ENDPTCTRL1 USBHS_EPCR1
	#define USB2_ENDPTCTRL2 USBHS_EPCR2
	#define USB2_ENDPTCTRL3 USBHS_EPCR3
	#define USB2_ENDPTCTRL4 USBHS_EPCR4
	#define USB2_ENDPTCTRL5 USBHS_EPCR5
	#define USB2_ENDPTCTRL6 USBHS_EPCR6
	#define USB2_ENDPTCTRL7 USBHS_EPCR7

	#define USB2_USBINTR USBHS_USBINTR
	#define USB2_PORTSC1 USBHS_PORTSC1

	#define USB2_ENDPTCOMPLETE USBHS_EPCOMPLETE
	#define USB2_ENDPTFLUSH USBHS_EPFLUSH 

	#define USB_USBCMD_ATDTW USBHS_USBCMD_ATDTW
	#define USB_USBCMD_SUTW USBHS_USBCMD_SUTW

	#define USB_USBSTS_UI USBHS_USBSTS_UI
	#define USB_USBSTS_SRI USBHS_USBSTS_SRI
	#define USB_USBSTS_UEI USBHS_USBSTS_UEI
	#define USB_USBSTS_SLI USBHS_USBSTS_SLI
	#define USB_USBSTS_PCI USBHS_USBSTS_PCI
	#define USB_USBSTS_TI1 USBHS_USBSTS_TI1
	#define USB_USBSTS_TI0 USBHS_USBSTS_TI0
	#define USB_USBSTS_URI USBHS_USBSTS_URI


	#define USB_DEVICEADDR_USBADRA USBHS_DEVICEADDR_USBADRA
	#define USB_DEVICEADDR_USBADR USBHS_DEVICEADDR_USBADR

	#define USB_USBINTR_SRE USBHS_USBINTR_SRE

	#define USB_PORTSC1_HSP USBHS_PORTSC_HSP
	#define USB_PORTSC1_PR USBHS_PORTSC_PR

	#define IRQ_USB2	IRQ_USBHS		

	#define USBPHY2_PWD		USBPHY_PWD	
	#define USBPHY2_CTRL	USBPHY_CTRL	
	#define USBPHY2_CTRL_CLR	USBPHY_CTRL_CLR		
	#define USBPHY2_CTRL_SET	USBPHY_CTRL_SET		
	#define USBPHY2_TRIM_OVERRIDE_EN_SET	USBPHY_TRIM_OVERRIDE_EN_SET
	#define USBPHY2_PLL_SIC	USBPHY_PLL_SIC

	#define	USB2_USBMODE	 USBHS_USBMODE

	#define	USB_USBCMD_RS USBHS_USBCMD_RS
	#define	USB_USBCMD_RST USBHS_USBCMD_RST

	#define	USB2_GPTIMER0CTRL USBHS_GPTIMER0CTL
	#define	USB2_GPTIMER0LD USBHS_GPTIMER0LD
	#define	USB2_GPTIMER1CTRL USBHS_GPTIMER1CTL
	#define	USB2_GPTIMER1LD USBHS_GPTIMER1LD
	
	#define	USB_GPTIMERCTRL_GPTRST USBHS_GPTIMERCTL_RST
	#define	USB_GPTIMERCTRL_GPTRUN USBHS_GPTIMERCTL_RUN
	
	#define	USB_USBINTR_UE USBHS_USBINTR_UE
	#define	USB_USBINTR_UEE USBHS_USBINTR_UEE
	#define	USB_USBINTR_URE USBHS_USBINTR_URE
	#define	USB_USBINTR_SLE USBHS_USBINTR_SLE
	#define	USB_USBINTR_TIE0 USBHS_USBINTR_TIE0

	#define	USB_USBMODE_CM_MASK	(uint32_t)((0x3) << 0)
	#define	USB_USBMODE_CM(n)	USBHS_USBMODE_CM(n)
	#define	USB_USBMODE_SLOM	USBHS_USBMODE_SLOM

	#define	USB2_ENDPOINTLISTADDR	USBHS_EPLISTADDR
	#define	USB2_TXFILLTUNING	USBHS_TXFILLTUNING

	#define USB_ENDPTCTRL_TXS	USBHS_EPCR_TXS	
	#define USB_ENDPTCTRL_RXS	USBHS_EPCR_RXS	
	
	#define USB2_BURSTSIZE	USBHS_BURSTSIZE	
	//
	//#define PMU_REG_3P0
	//#define PMU_REG_3P0_ENABLE_LINREG
	//#define CCM_CCGR6
	
	//#define 	CCM_CCGR_ON
	//#define 	HW_OCOTP_MAC0


	
/*
// from usbhost_t3 (oposite definitions)

#define USBHS_USBCMD		USB2_USBCMD
#define USBHS_USBSTS		USB2_USBSTS
#define USBHS_USBINTR		USB2_USBINTR
#define USBHS_FRINDEX		USB2_FRINDEX
#define USBHS_PERIODICLISTBASE	USB2_PERIODICLISTBASE
#define USBHS_ASYNCLISTADDR	USB2_ASYNCLISTADDR
#define USBHS_PORTSC1		USB2_PORTSC1

#define USBHS_USBCMD_ASE	USB_USBCMD_ASE
#define USBHS_USBCMD_IAA	USB_USBCMD_IAA
#define USBHS_USBCMD_RST	USB_USBCMD_RST
#define USBHS_USBCMD_ITC(n)	USB_USBCMD_ITC(n)
#define USBHS_USBCMD_RS		USB_USBCMD_RS
#define USBHS_USBCMD_ASP(n)	USB_USBCMD_ASP(n)
#define USBHS_USBCMD_ASPE	USB_USBCMD_ASPE
#define USBHS_USBCMD_PSE	USB_USBCMD_PSE
#define USBHS_USBCMD_FS2	USB_USBCMD_FS_2
#define USBHS_USBCMD_FS(n)	USB_USBCMD_FS_1(n)		

#define USBHS_USBSTS_AAI	USB_USBSTS_AAI
#define USBHS_USBSTS_AS		USB_USBSTS_AS
// UAI & UPI bits are undocumented in IMXRT, K66 pg 1602, RT1050 pg 2374
#define USBHS_USBSTS_UAI	((uint32_t)(1<<18))
#define USBHS_USBSTS_UPI	((uint32_t)(1<<19))
#define USBHS_USBSTS_UEI	USB_USBSTS_UEI
#define USBHS_USBSTS_PCI	USB_USBSTS_PCI
#define USBHS_USBSTS_TI0	USB_USBSTS_TI0
#define USBHS_USBSTS_TI1	USB_USBSTS_TI1
#define USBHS_USBSTS_SEI	USB_USBSTS_SEI
#define USBHS_USBSTS_URI	USB_USBSTS_URI
#define USBHS_USBSTS_SLI	USB_USBSTS_SLI
#define USBHS_USBSTS_HCH	USB_USBSTS_HCH
#define USBHS_USBSTS_NAKI	USB_USBSTS_NAKI

#define USBHS_USBINTR_PCE	USB_USBINTR_PCE
#define USBHS_USBINTR_TIE0	USB_USBINTR_TIE0
#define USBHS_USBINTR_TIE1	USB_USBINTR_TIE1
#define USBHS_USBINTR_SEE	USB_USBINTR_SEE
#define USBHS_USBINTR_UPIE	USB_USBINTR_UPIE
#define USBHS_USBINTR_UAIE	USB_USBINTR_UAIE

#define USBHS_PORTSC_PP		USB_PORTSC1_PP
#define USBHS_PORTSC_OCC	USB_PORTSC1_OCC
#define USBHS_PORTSC_PEC	USB_PORTSC1_PEC
#define USBHS_PORTSC_CSC	USB_PORTSC1_CSC
#define USBHS_PORTSC_CCS	USB_PORTSC1_CCS
#define USBHS_PORTSC_PE		USB_PORTSC1_PE
#define USBHS_PORTSC_HSP	USB_PORTSC1_HSP
#define USBHS_PORTSC_FPR	USB_PORTSC1_FPR
#define USBHS_PORTSC_PR		USB_PORTSC1_PR



// TODO: what is the best setting for this register on IMXRT ???
#define USBHS_USB_SBUSCFG	USB2_SBUSCFG
*/
#endif